### PR TITLE
update

### PR DESCRIPTION
**Pull request by LuanJian**
1.Update the Chinese language of new function button synchronously。
2.Hope to be added to the software built-in language for more Chinese users to use.

Thank you again.

### CODE REVIEW

**Comment by AnLinkSoft** [comment]
Thanks. We would like to integrate Chinese language into package, but we are not permitted to use these translations from community. Also translation files can't be synchronized with.
We are looking forward a Chinese agent company to cooperate with us in next few months, to keep the quality and in time.

**Comment by LuanJian** [comment]
Before that, can you add instructions to tell the user where to download and use these language files?It's sad that I can't see the instructions directly from the software or the official website.Can we add relevant instructions in the "add language" section of the software or in the "website"? Will this bring some convenience to the users?I sincerely hope that Anlink can do better and better to bring convenience to more and more users.Before solving the problem, I also hope that I can help you in this way. I hope that more Chinese users can use such excellent software.

**Comment by AnLinkSoft** [comment]
We are working on downloading page.

**Comment by LuanJian** [comment]
This is great news, thanks again!

**Comment by AnLinkSoft** [comment]
A lot of features are in our road map so please be patient. And thanks for your translation.

**Comment by LuanJian** [comment]
It is also my honor to witness the growth of a great software.

**Pull request merged**
